linters:  
  enable:  
    - unused  
    - goconst  
    - gocyclo  
    - gofmt  
    - goimports  
    - ineffassign  
    - misspell  
    - typecheck  
    - unused  
    - errcheck  


issues:  
  exclude-use-default: false  
  exclude:  
    - "Error return value is not checked"  
    - "G101"  


run:  
  timeout: 5m  
  
output:  
  formats: json  


paths:  
  include:  
    - ./...  
  exclude:  
    - vendor  


gocyclo:  
  min-complexity: 15   


exclude-rules:  
  - path: _test\.go  
    text: "ignore all test files"