# version: '3.8'

# services:

#   db:
#     restart: always
#     image: postgres:latest
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: postgres
      
#     volumes:
#       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#       - ./pgdata:/postgresql/data
#     ports:
#       - 5432:5432
version: '3.8'

services:

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

# version: '3.3'  

# services:  
#   app:  
#     build: .  
#     ports:  
#       - "8080:8080"  
#     depends_on:  
#       - db  

#   db:  
#     restart: always  
#     image: postgres:latest  
#     environment:  
#       POSTGRES_USER: postgres  
#       POSTGRES_PASSWORD: postgres  
#       POSTGRES_DB: postgres  
#     volumes:  
#       - ./init.sql:/docker-entrypoint-initdb.d/init.sql  
#       - pgdata:/var/lib/postgresql/data  
#     ports:  
#       - "5432:5432"  

# volumes:  
#   pgdata: