version: '3.8'

services:

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080

  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    ports:
      - 5432:5432

  initdb:
    image: postgres:latest 
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    
    
